package CellularAutomata.Diffusion;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import Component.BasicProcessor.genr;
import javafx.application.Application;
import javafx.stage.Stage;
import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class HeatDiffusion extends TwoDimCellSpace {

	public HeatDiffusion() {
		this(2, 5);
	}

	public HeatDiffusion(int xDim, int yDim) {
		super("Heat Diffusion", xDim, yDim);

		HeatTrans ht = new HeatTrans(xDim, yDim);
		add(ht);

		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				HeatCell heatcell = new HeatCell(i, j);
				addCell(heatcell);

				if (i == 0) {
					heatcell.isSource = 1;
				}
				heatcell.initialize();

				addCoupling(ht, ht.getOutPortsNames()[i][j], heatcell, "inTrans");

			}
		}

		doNeighborToNeighborCoupling();
		coupleAllTo("outTrans", ht, "inComp");

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(925, 790);
        ((ViewableComponent)withName("Cell: 0, 1")).setPreferredLocation(new Point(222, 206));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(1, 210));
        ((ViewableComponent)withName("Cell: 1, 1")).setPreferredLocation(new Point(-5, 487));
        ((ViewableComponent)withName("Cell: -1, -1")).setPreferredLocation(new Point(491, 319));
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(220, 493));
    }
}
