package CellularAutomata.MOL;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import Component.BasicProcessor.genr;
import javafx.application.Application;
import javafx.stage.Stage;
import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class HeatDiffusionWTime extends TwoDimCellSpace {

	public HeatDiffusionWTime() {
		this(100, 20);
	}

	public HeatDiffusionWTime(int xDim, int yDim) {
		super("Heat Diffusion", xDim, yDim);

		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				MOLCell molcell = new MOLCell(i, j);
				addCell(molcell);

				if (i == 0 && j!= 0 && j != yDimCellspace-1) {
					molcell.isSource = 1;
				}
				if( j == 0 || j == yDimCellspace-1)
				{
					molcell.isBorder = 1;
				}
				
				molcell.initialize();
			}
		}

		doNeighborToNeighborCoupling();

	}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1146, 1067);
        ((ViewableComponent)withName("Cell: 2, 4")).setPreferredLocation(new Point(670, 848));
        ((ViewableComponent)withName("Cell: 1, 2")).setPreferredLocation(new Point(351, 439));
        ((ViewableComponent)withName("Cell: 1, 4")).setPreferredLocation(new Point(361, 848));
        ((ViewableComponent)withName("Cell: 2, 3")).setPreferredLocation(new Point(660, 646));
        ((ViewableComponent)withName("Cell: 0, 1")).setPreferredLocation(new Point(42, 245));
        ((ViewableComponent)withName("Cell: 1, 3")).setPreferredLocation(new Point(353, 637));
        ((ViewableComponent)withName("Cell: 0, 4")).setPreferredLocation(new Point(47, 843));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(41, 47));
        ((ViewableComponent)withName("Cell: 2, 2")).setPreferredLocation(new Point(660, 442));
        ((ViewableComponent)withName("Cell: 1, 1")).setPreferredLocation(new Point(350, 254));
        ((ViewableComponent)withName("Cell: 2, 1")).setPreferredLocation(new Point(660, 248));
        ((ViewableComponent)withName("Cell: 2, 0")).setPreferredLocation(new Point(650, 51));
        ((ViewableComponent)withName("Cell: 0, 2")).setPreferredLocation(new Point(35, 448));
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(349, 52));
        ((ViewableComponent)withName("Cell: 0, 3")).setPreferredLocation(new Point(39, 633));
    }
}
