package Component.TestFixtures.Homework;

import java.awt.Dimension;
import java.awt.Point;

import Component.TestFixtures.Homework.proc;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class pipeline extends ViewableDigraph
{
    public pipeline()
    {
        this("pipeline", 10.0);
    }
    
    public pipeline(String name, double proc_time)
    {
        super(name);

        ViewableAtomic proc1 = new proc("proc1", proc_time/2);
        ViewableAtomic proc2 = new proc("proc2", proc_time/2);
        
        add(proc1);
        add(proc2);

        addCoupling(this, "in", proc1, "in");
        addCoupling(proc1,"out",proc2,"in");
        addCoupling(proc2,"out",this,"out");
        
        addInport("in");
        addOutport("out");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(499, 105);
        ((ViewableComponent)withName("proc2")).setPreferredLocation(new Point(197, 41));
        ((ViewableComponent)withName("proc1")).setPreferredLocation(new Point(-5, 30));
    }
}
