package CellularAutomata.DiffusionInternal;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import Component.BasicProcessor.genr;
import javafx.application.Application;
import javafx.stage.Stage;
import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class HeatDiffusion extends TwoDimCellSpace {

	public HeatDiffusion() {
		this(10,10);
	}

	public HeatDiffusion(int xDim, int yDim) {
		super("Heat Diffusion", xDim, yDim);

		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				HeatCell heatcell = new HeatCell(i, j);
				addCell(heatcell);

				if (i == 0) {
					heatcell.isSource = 1;
				}
				heatcell.initialize();

			}
		}

		doNeighborToNeighborCoupling();


	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 538);
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(221, 292));
        ((ViewableComponent)withName("Cell: 0, 1")).setPreferredLocation(new Point(10, 274));
        ((ViewableComponent)withName("Cell: 1, 1")).setPreferredLocation(new Point(226, 82));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(20, 61));
    }
}
