package CellularAutomata.Diffusion2;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import Component.BasicProcessor.genr;
import javafx.application.Application;
import javafx.stage.Stage;
import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class HeatDiffusion extends TwoDimCellSpace {

	public HeatDiffusion() {
		this(1000, 1000);
	}

	public HeatDiffusion(int xDim, int yDim) {
		super("Heat Diffusion", xDim, yDim);

		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				HeatCell heatcell = new HeatCell(i, j);
				addCell(heatcell);

				if (i == 0 || i == xDimCellspace-1) {
					heatcell.isSource = 1;
				}
				heatcell.initialize();
			}
		}

		doNeighborToNeighborCoupling();

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1282, 1040);
        ((ViewableComponent)withName("Cell: 7, 0")).setPreferredLocation(new Point(589, 593));
        ((ViewableComponent)withName("Cell: 5, 0")).setPreferredLocation(new Point(267, 593));
        ((ViewableComponent)withName("Cell: 6, 0")).setPreferredLocation(new Point(401, 584));
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(214, 38));
        ((ViewableComponent)withName("Cell: 8, 0")).setPreferredLocation(new Point(793, 592));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(6, 37));
        ((ViewableComponent)withName("Cell: 2, 0")).setPreferredLocation(new Point(415, 40));
        ((ViewableComponent)withName("Cell: 3, 0")).setPreferredLocation(new Point(633, 42));
        ((ViewableComponent)withName("Cell: 4, 0")).setPreferredLocation(new Point(887, 45));
    }
}
