package CellularAutomata.CarMoving2DAsync;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Random;

import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableComponent;

public class AgentSpace extends TwoDimCellSpace
{

    private final String[] statusCXCL12 = { "EMPTY", "EMPTY", "EMPTY", "Car1" };
    private final String[] statusCXCLR4 = { "EMPTY", "EMPTY", "EMPTY", "Car2" };
    private final String[] statusCXCLR7 = { "EMPTY", "EMPTY", "EMPTY", "Car3" };

    public AgentSpace() {
        this(50, 3);
    }

    public AgentSpace(int xDim, int yDim) {
        super("Chemotaxis", xDim, yDim);

        this.numCells = xDim * yDim;
        for (int i = 0; i < xDimCellspace; i++) {
            for (int j = 0; j < yDimCellspace; j++) {
                Random randomno = new Random();
                Agent cell;
                if (i <= xDimCellspace / 3) {
                    cell = new Agent(i, j, statusCXCL12[randomno.nextInt(statusCXCL12.length)], 3);
                } else if (i >= xDimCellspace / 3 * 2) {
                    cell = new Agent(i, j, statusCXCLR4[randomno.nextInt(statusCXCLR4.length)], 3);
                } else {
                    cell = new Agent(i, j, statusCXCLR7[randomno.nextInt(statusCXCLR7.length)], 3);
                }
                addCell(cell);
                cell.initialize();
            }
        }

        doNeighborToNeighborCoupling();

    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1579, 332);
        ((ViewableComponent)withName("Cell: 1, 0")).setPreferredLocation(new Point(148, 52));
        ((ViewableComponent)withName("Cell: 3, 0")).setPreferredLocation(new Point(527, 52));
        ((ViewableComponent)withName("Cell: 5, 0")).setPreferredLocation(new Point(902, 52));
        ((ViewableComponent)withName("Cell: 7, 0")).setPreferredLocation(new Point(1271, 52));
        ((ViewableComponent)withName("Cell: 0, 0")).setPreferredLocation(new Point(-45, 52));
        ((ViewableComponent)withName("Cell: 2, 0")).setPreferredLocation(new Point(338, 52));
        ((ViewableComponent)withName("Cell: 6, 0")).setPreferredLocation(new Point(1084, 52));
        ((ViewableComponent)withName("Cell: 4, 0")).setPreferredLocation(new Point(712, 52));
    }
}
