/**
 * DEVS-Suite Simulator
 * Arizona Center for Integrative Modeling & Simulation
 * Arizona State University, Tempe, AZ, USA
 *
 * Author(s): H.S. Sarjoughian
 */

package Component.MapSearchDevice;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class EF_MSD extends ViewableDigraph {
	private final static double SimDuration = 80.0;
	
	private final static double GreenTA = 3.6;
	private final static double RedTA = 6.7;
	
	private final static double SearchTA = 2.0;
	private final static double UpdateTA = 7.0;
	private final static double InterruptTA = 0.3;

	public EF_MSD() {
		super("EF_MSD");

		ViewableDigraph ExpFrame = new ExpFrame("expFrame", SimDuration, GreenTA, RedTA);
		
		ViewableAtomic MSD = new MSD("MSD", SearchTA, UpdateTA, InterruptTA);

		add(ExpFrame);
		add(MSD);



		addCoupling(MSD, "outGreen", ExpFrame, "searched");
		addCoupling(MSD, "outRed", ExpFrame, "updated");
		
		addCoupling(ExpFrame, "outGreen", MSD, "inGreen");
		addCoupling(ExpFrame, "outRed", MSD, "inRed");
		

	}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1002, 581);
        ((ViewableComponent)withName("MSD")).setPreferredLocation(new Point(324, 71));
        ((ViewableComponent)withName("expFrame")).setPreferredLocation(new Point(50, 50));
    }
}


