/**
 * DEVS-Suite Simulator
 * Arizona Center for Integrative Modeling & Simulation
 * Arizona State University, Tempe, AZ, USA
 *
 * Author(s): H.S. Sarjoughian
 */

package Component.MapSearchDevice;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class ExpFrame extends ViewableDigraph {

	public ExpFrame(String name, double simDuration, double greenTA, double redTA) {
		super(name);

		ViewableDigraph Generator = new Generator("generator", greenTA, redTA);
		ViewableAtomic Transducer = new Transducer("transducer", simDuration);

		add(Generator);
		add(Transducer);

		addInport("searched");
		addInport("updated");
		
		addOutport("outGreen");
		addOutport("outRed");

		addCoupling(this, "searched", Transducer, "Tsearched");
		addCoupling(this, "updated", Transducer, "updated");
		
		addCoupling(Generator, "outGreen", this, "outGreen");
		addCoupling(Generator, "outRed", this, "outRed");
		
		addCoupling(Transducer, "stop", Generator, "stop");
		
		addCoupling(Generator, "outRed", Transducer, "updateStart");

	}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(792, 261);
        ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(338, 106));
        ((ViewableComponent)withName("generator")).setPreferredLocation(new Point(10, 80));
    }
}

