package Component.TestFixtures.Workstation;

import java.awt.Dimension;
import java.awt.Point;

import Component.TestFixtures.Buffer.buffer;
import Component.TestFixtures.Homework.proc;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class ws extends ViewableDigraph
{
    public ws()
    {
        this("ws", 10.0, 10);
    }

    public ws(String name, double proc_time, int capacity)
    {
        super(name);
        
        ViewableAtomic b = new buffer("buffer",1,capacity);
        ViewableAtomic p = new proc("proc",proc_time);

        add(b);
        add(p);
        
        addInport("in");
        addOutport("out");
        addOutport("fail");

        addCoupling(this,"in",b,"in");

        addCoupling(b,"out",p,"in");
        addCoupling(b,"balked",this,"fail");

        addCoupling(p,"out",this,"out");
        addCoupling(p,"out",b,"release");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(514, 163);
        ((ViewableComponent)withName("proc")).setPreferredLocation(new Point(228, 104));
        ((ViewableComponent)withName("buffer")).setPreferredLocation(new Point(36, 52));
    }
}
