package CellularAutomata.ForestFire;

import java.awt.Dimension;
import java.awt.Point;

import javafx.application.Application;
import javafx.stage.Stage;
import model.modeling.CAModels.TwoDimCellSpace;
import view.modeling.ViewableComponent;
import view.modeling.ViewableComponentUtil;

public class ForestOnFire extends TwoDimCellSpace {

	public ForestOnFire() {
		this(10, 10);
	}

	public ForestOnFire(int xDim, int yDim) {
		super("forest", xDim, yDim);
		this.numCells = xDim * yDim;
		for (int i = 0; i < xDimCellspace; i++) {
			for (int j = 0; j < yDimCellspace; j++) {
				Tree tree = new Tree(i, j);
				addCell(tree);
			}
		}

		// Do the couplings

		doNeighborToNeighborCoupling();

	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(800, 700);
        ((ViewableComponent)withName("Cell_key = 1 ,value = 1")).setPreferredLocation(new Point(-8, 245));
        ((ViewableComponent)withName("Cell_key = 1 ,value = 0")).setPreferredLocation(new Point(-4, 32));
        ((ViewableComponent)withName("Cell_key = 0 ,value = 1")).setPreferredLocation(new Point(196, 250));
        ((ViewableComponent)withName("Cell_key = 0 ,value = 0")).setPreferredLocation(new Point(174, 50));
    }
}
